from __future__ import annotations

from typing import Any, Iterable, Literal, overload

import numpy as np
from numpy.typing import NDArray


FloatArray1D = NDArray[np.float32]
FloatArray2D = NDArray[np.float32]
IntArray1D = NDArray[np.int32]
FP_DTYPE: Any


class _HarmonicsView:
    ampl: FloatArray2D
    phse: FloatArray2D
    nhar: IntArray1D


class AnalysisOptions:
    ptr: Any
    thop: float
    maxnhar: int
    maxnhar_e: int
    npsd: int
    lip_radius: float
    f0_refine: int
    hm_method: int
    rel_winsize: float
    def __init__(self, ptr: Any = ..., owns_memory: bool = ..., **kwargs: Any) -> None: ...
    def __enter__(self) -> AnalysisOptions: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def nchannel(self) -> int: ...
    @nchannel.setter
    def nchannel(self, value: int) -> None: ...
    @property
    def chanfreq(self) -> FloatArray1D: ...
    @chanfreq.setter
    def chanfreq(self, value: Iterable[float]) -> None: ...
    def close(self) -> None: ...


class SynthesisOptions:
    ptr: Any
    fs: float
    use_iczt: int
    use_l1: int
    iczt_param_a: float
    iczt_param_b: float
    def __init__(self, fs: float | None = ..., ptr: Any = ..., owns_memory: bool = ..., **kwargs: Any) -> None: ...
    def __enter__(self) -> SynthesisOptions: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...


class Chunk:
    ptr: Any
    @classmethod
    def allocate_layer0(
        cls,
        nfrm: int,
        *,
        fs: float,
        max_nhar: int,
        options: AnalysisOptions | Any | None = ...,
    ) -> Chunk: ...
    @classmethod
    def allocate_layer1(
        cls,
        nfrm: int,
        *,
        fs: float,
        nspec: int,
        max_nhar: int,
        options: AnalysisOptions | Any | None = ...,
    ) -> Chunk: ...
    @classmethod
    def from_layer0_arrays(
        cls,
        f0: Iterable[float],
        ampl: FloatArray2D,
        phse: FloatArray2D,
        nhar: Iterable[int] | None = ...,
        *,
        fs: float,
        options: AnalysisOptions | Any | None = ...,
    ) -> Chunk: ...
    @classmethod
    def from_layer1_arrays(
        cls,
        f0: Iterable[float],
        rd: Iterable[float],
        vtmagn: FloatArray2D,
        vsphse: FloatArray2D,
        *,
        fs: float,
        vsphse_lengths: Iterable[int] | None = ...,
        options: AnalysisOptions | Any | None = ...,
    ) -> Chunk: ...
    def __init__(self, ptr: Any, owns_memory: bool = ...) -> None: ...
    def __enter__(self) -> Chunk: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def copy(self) -> Chunk: ...
    @property
    def nfrm(self) -> int: ...
    @property
    def f0(self) -> FloatArray1D: ...
    @f0.setter
    def f0(self, value: Iterable[float]) -> None: ...
    @property
    def nhar(self) -> IntArray1D: ...
    @nhar.setter
    def nhar(self, value: Iterable[int]) -> None: ...
    @property
    def ampl(self) -> FloatArray2D: ...
    @ampl.setter
    def ampl(self, values: FloatArray2D) -> None: ...
    @property
    def phse(self) -> FloatArray2D: ...
    @phse.setter
    def phse(self, values: FloatArray2D) -> None: ...
    @property
    def rd(self) -> FloatArray1D: ...
    @rd.setter
    def rd(self, values: Iterable[float]) -> None: ...
    @property
    def vtmagn(self) -> FloatArray2D: ...
    @vtmagn.setter
    def vtmagn(self, values: FloatArray2D) -> None: ...
    @property
    def vsphse(self) -> FloatArray2D: ...
    @vsphse.setter
    def vsphse(self, values: FloatArray2D) -> None: ...
    @property
    def vsphse_lengths(self) -> IntArray1D: ...
    @vsphse_lengths.setter
    def vsphse_lengths(self, lengths: Iterable[int]) -> None: ...
    @property
    def nspec(self) -> int: ...
    def frame_f0(self) -> FloatArray1D: ...
    def set_frame_f0(self, f0: Iterable[float]) -> None: ...
    def frame_nhar(self) -> IntArray1D: ...
    def get_frame_harmonics(self, frame_idx: int) -> tuple[FloatArray1D, FloatArray1D]: ...
    def set_frame_harmonics(self, frame_idx: int, ampl: Iterable[float], phse: Iterable[float]) -> None: ...
    def to_layer1(self, nfft: int) -> None: ...
    def to_layer0(self) -> None: ...
    def phasesync_rps(self, layer1_based: bool = ...) -> None: ...
    def phasepropagate(self, sign: int = ...) -> None: ...
    def harmonics(self, fill_value: float = ...) -> _HarmonicsView: ...
    def set_harmonics(self, ampl: FloatArray2D, phse: FloatArray2D, nhar: Iterable[int] | None = ...) -> None: ...
    def clear_member(self, member_idx: int, mask: Iterable[int] | Iterable[bool] | None = ...) -> None: ...
    def enable_pulse_by_pulse(self, mask: Iterable[int] | Iterable[bool], clear_harmonics: bool = ...) -> None: ...
    def frame_scalar(self, member_idx: int, default: float = ...) -> FloatArray1D: ...
    def set_frame_scalar(self, member_idx: int, values: Iterable[float]) -> None: ...
    def resample_linear_f0(self, nfrm_new: int) -> Chunk: ...
    def pitch_shift_layer1(self, ratio: float, compensate_vtmagn_db: bool = ..., clear_harmonics: bool = ...) -> None: ...


class Layer0Features:
    ptr: Any
    @classmethod
    def from_arrays(
        cls,
        f0: Iterable[float],
        ampl: FloatArray2D,
        phse: FloatArray2D,
        nhar: Iterable[int] | None = ...,
        *,
        fs: float,
        options: AnalysisOptions | Any | None = ...,
    ) -> Layer0Features: ...
    def __init__(self, chunk: Chunk | Any, *, validate: bool = ..., owns_memory: bool = ...) -> None: ...
    def __enter__(self) -> Layer0Features: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def ptr(self) -> Any: ...
    @property
    def nfrm(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def f0(self) -> FloatArray1D: ...
    @f0.setter
    def f0(self, value: Iterable[float]) -> None: ...
    def close(self) -> None: ...
    def copy_chunk(self) -> Chunk: ...
    def phasepropagate(self, sign: int = ...) -> None: ...
    def phasesync_rps(self, layer1_based: bool = ...) -> None: ...
    @property
    def nhar(self) -> IntArray1D: ...
    @nhar.setter
    def nhar(self, value: Iterable[int]) -> None: ...
    @property
    def ampl(self) -> FloatArray2D: ...
    @ampl.setter
    def ampl(self, values: FloatArray2D) -> None: ...
    @property
    def phse(self) -> FloatArray2D: ...
    @phse.setter
    def phse(self, values: FloatArray2D) -> None: ...
    def copy(self) -> Layer0Features: ...
    def frame_scalar(self, member_idx: int, default: float = ...) -> FloatArray1D: ...
    def set_frame_scalar(self, member_idx: int, values: Iterable[float]) -> None: ...
    def clear_member(self, member_idx: int, mask: Iterable[int] | Iterable[bool] | None = ...) -> None: ...
    def enable_pulse_by_pulse(self, mask: Iterable[int] | Iterable[bool], clear_harmonics: bool = ...) -> None: ...
    def resample_linear_f0(self, nfrm_new: int) -> Layer0Features: ...
    def to_layer1(self, nfft: int) -> Layer1Features: ...


class Layer1Features:
    ptr: Any
    @classmethod
    def from_arrays(
        cls,
        f0: Iterable[float],
        rd: Iterable[float],
        vtmagn: FloatArray2D,
        vsphse: FloatArray2D,
        *,
        fs: float,
        vsphse_lengths: Iterable[int] | None = ...,
        options: AnalysisOptions | Any | None = ...,
    ) -> Layer1Features: ...
    def __init__(self, chunk: Chunk | Any, *, validate: bool = ..., owns_memory: bool = ...) -> None: ...
    def __enter__(self) -> Layer1Features: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def ptr(self) -> Any: ...
    @property
    def nfrm(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def f0(self) -> FloatArray1D: ...
    @f0.setter
    def f0(self, value: Iterable[float]) -> None: ...
    def close(self) -> None: ...
    def copy_chunk(self) -> Chunk: ...
    def phasepropagate(self, sign: int = ...) -> None: ...
    def phasesync_rps(self, layer1_based: bool = ...) -> None: ...
    @property
    def rd(self) -> FloatArray1D: ...
    @rd.setter
    def rd(self, values: Iterable[float]) -> None: ...
    @property
    def vtmagn(self) -> FloatArray2D: ...
    @vtmagn.setter
    def vtmagn(self, values: FloatArray2D) -> None: ...
    @property
    def vsphse(self) -> FloatArray2D: ...
    @vsphse.setter
    def vsphse(self, values: FloatArray2D) -> None: ...
    @property
    def vsphse_lengths(self) -> IntArray1D: ...
    @property
    def nspec(self) -> int: ...
    def copy(self) -> Layer1Features: ...
    def enable_pulse_by_pulse(self, mask: Iterable[int] | Iterable[bool], clear_harmonics: bool = ...) -> None: ...
    def resample_linear_f0(self, nfrm_new: int) -> Layer1Features: ...
    def pitch_shift(self, ratio: float, compensate_vtmagn_db: bool = ..., clear_harmonics: bool = ...) -> None: ...
    def to_layer0(self) -> Layer0Features: ...


class Coder:
    ptr: Any
    def __init__(self, conf_or_chunk: Any, order_spec: int = ..., order_bap: int = ..., ptr: Any = ..., owns_memory: bool = ...) -> None: ...
    def __enter__(self) -> Coder: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def encode_frame(self, frame: Any) -> FloatArray1D: ...
    def reconstruct_chunk(
        self,
        chunk: Chunk | Any,
        decode_layer0: bool = ...,
        decode_layer1: bool = ...,
    ) -> Layer0Features | Layer1Features | tuple[Layer0Features, Layer1Features]: ...


class RTSynthBuffer:
    ptr: Any
    def __init__(self, options: Any, conf_or_chunk: Any, capacity_samples: int = ..., ptr: Any = ..., owns_memory: bool = ...) -> None: ...
    def __enter__(self) -> RTSynthBuffer: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    @property
    def latency(self) -> int: ...
    def clear(self) -> None: ...
    def render_chunk_decomposed(self, chunk: Chunk | Any, nx: int, trim_latency: bool = ...) -> dict[str, FloatArray1D]: ...


class Output:
    ptr: Any
    def __init__(self, ptr: Any, owns_memory: bool = ...) -> None: ...
    def __enter__(self) -> Output: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    @property
    def y(self) -> FloatArray1D: ...
    @property
    def y_sin(self) -> FloatArray1D: ...
    @property
    def y_noise(self) -> FloatArray1D: ...
    @property
    def ny(self) -> int: ...
    @property
    def fs(self) -> float: ...
    def __array__(self, dtype: Any = ...) -> FloatArray1D: ...


@overload
def analyze_chunk(
    options: AnalysisOptions | Any,
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    return_xap: Literal[False] = ...,
) -> Chunk: ...
@overload
def analyze_chunk(
    options: AnalysisOptions | Any,
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    return_xap: Literal[True],
) -> tuple[Chunk, FloatArray1D]: ...
def analyze_chunk(
    options: AnalysisOptions | Any,
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    return_xap: bool = ...,
) -> Chunk | tuple[Chunk, FloatArray1D]: ...


def synthesize(options: SynthesisOptions | Any, chunk: Chunk | Any) -> Output: ...
def synthesize_output(options: SynthesisOptions | Any, chunk: Chunk | Any) -> Output: ...


@overload
def analyze(
    options: AnalysisOptions | Any,
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    return_xap: Literal[False] = ...,
) -> Layer0Features: ...
@overload
def analyze(
    options: AnalysisOptions | Any,
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    return_xap: Literal[True],
) -> tuple[Layer0Features, FloatArray1D]: ...
def analyze(
    options: AnalysisOptions | Any,
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    return_xap: bool = ...,
) -> Layer0Features | tuple[Layer0Features, FloatArray1D]: ...


def to_layer1(features: Layer0Features | Chunk | Any, nfft: int) -> Layer1Features: ...
def to_layer0(features: Layer1Features | Chunk | Any) -> Layer0Features: ...
def warp_frequency(fmin: float, fmax: float, n: int, warp_const: float) -> FloatArray1D: ...
def spectral_mean(spectrum: Iterable[float], fnyq: float, freq_axis: Iterable[float]) -> FloatArray1D: ...
def spectrum_from_envelope(freq_axis: Iterable[float], env: Iterable[float], nspec: int, fnyq: float) -> FloatArray1D: ...
def harmonic_analysis(
    x: Iterable[float],
    fs: float,
    f0: Iterable[float],
    thop: float,
    rel_winsize: float = ...,
    maxnhar: int = ...,
    method: int = ...,
    pad_value: float = ...,
) -> dict[str, Any]: ...
def synthesize_harmonic_frame(
    ampl: Iterable[float],
    phse: Iterable[float],
    f0: float,
    nx: int,
    use_iczt: bool = ...,
) -> FloatArray1D: ...
def qifft(magn: Iterable[float], k: int) -> tuple[float, float]: ...
def spec2env(S: Iterable[float], nfft: int, f0_ratio: float, nhar: int, Cout: Iterable[float] | None = ...) -> FloatArray1D: ...
def lfmodel_from_rd(rd: float, T0: float, Ee: float) -> Any: ...
@overload
def lfmodel_spectrum(model: Any, freq: Iterable[float], return_phase: Literal[False] = ...) -> FloatArray1D: ...
@overload
def lfmodel_spectrum(model: Any, freq: Iterable[float], return_phase: Literal[True]) -> tuple[FloatArray1D, FloatArray1D]: ...
def lfmodel_spectrum(model: Any, freq: Iterable[float], return_phase: bool = ...) -> FloatArray1D | tuple[FloatArray1D, FloatArray1D]: ...
def lfmodel_period(model: Any, fs: int, n: int) -> FloatArray1D: ...
def ifdetector_estimate(ifd: Any, x: Iterable[float]) -> float: ...
